### DISCUSSION TITLE
Physical Printing

### DISCUSSION THREAD

**Discussion by Gazook89** [naturalcrit/homebrewery#4150] [General]
Here is a place where we can drop notes about the process of actually printing a brew to paper, either on a home printer or sent to a commercial service.  This process has some special considerations that I think are worth noting-- maybe to be considered for future features or improvements, but also just as a resource for any users who might want to go down this path.  

**If you, reading this, have ever sent your Homebrewery document to a commercial printer (either local shop or online service), please let us know here how the experience went!**  I'd personally love to know the pain points and hot tips you might have.  

For now, here is the first actual experience I've heard from a user about the process:

> My process of getting it ready for print was:
> 1. Change the page size to A4+margins, which affected the layout so I basically had to redo it
> 2. Export without footnote and header images as an A3 size because Homebrewery doesn't understand print margins
> 3. Lay it out page by page in Gimp with the added footnote images
> 4. Export that into a PDF
> 5. Open the PDF in Krita, then convert to the CMYK color space
> 6. Brighten and desaturate where necessary page by page
> 7. Export each page as a separate .tif image with the profile color embedded, named with the page number
> 8. Send all the .tif images to print

> The Step 3 with gimp was the most tedious

![image](https://github.com/user-attachments/assets/2b06769b-f44e-41a8-a990-35d65ee28928)

The user printed a shorter adventure booklet.  Here is the result:

![image](https://github.com/user-attachments/assets/1f2d1062-8acd-4ff6-b4b9-0d26eb1ac576)

From the user's adventure, [on Itch.io here](https://navypink.itch.io/black-lilies)

**Comment by Gazook89** [comment]
And the link to [Drive-Thru RPG's requirements for print-on-demand](https://help.drivethrupartners.com/hc/en-us/articles/12780800178583-Quick-Specifications-for-Print-Books#h_01HFVSQQNE7CNT9CBGDAMQC835)

Partial requirements -- omitted the Cover and page signatures requirements:

- **File format**: PDF (.pdf). Your cover template must be generated using our Template Generator.
- **PDF Output Compliance**: PDF/X-1a:2001 or PDF/X-3:2002
- **Color Space**: 
  - For color covers and interiors, use CMYK. 
  - Do not use RGB, Lab, or spot colors (PMS / PANTONE). 
  - For black & white interiors, use grayscale.
- **Ink Coverage**:
  - Total ink coverage should not exceed 240%.
  - Use the CGATS21_CRPC1.icc color profile to keep your book in range. 
    - To learn how to install and to check your ink coverage, visit our Correcting Most Common Print Errors article.
  - **Black Text Density**: 
    - We recommend a rich black with CMYK values of 60% Cyan (C), 40% Magenta (M), 40% Yellow (Y), and 100% Black (K).
    - When using text that is 24 pt. or below, use 100% black only: 
      - i.e., CMYK values of 0% Cyan (C), 0% Magenta (M), 0% Yellow (Y), and 100% Black (K).
    - Never use Registration Black.
- **Image Resolution**:
  - 300 dots per inch (dpi) for CMYK or Grayscale.
  - 600 dpi for black & white line art.
    - Dimensions of your images should be the same size (i.e., in inches) as you’d want it to print in your physical book.
  - Preferred image formats are TIFF or EPS files.
- **LPI (lines per inch)**:
  - Premium color and covers - 180
  - Standard color - 175
  - Black and white - 106
- **Fonts**: All fonts must be embedded.
- **Bleed**: 
  - All books need a .125" bleed on the three outside (non-binding) edges. 
  - Do NOT add bleed to the inside (binding) edge.
  - **Crop Marks**: Do not include crop, printer, or registration marks in a file.
- **Margins/Safety**: 
  - All text is recommended to be a minimum of 0.5” inside the page edge, 
  - Non-bleeding art should have a safety of 0.25" from the page edge on the outside three edges and 0.5" on the binding edge. 
  - Text or images too close to the page edges may be trimmed during printing.

**Comment by Gazook89** [comment]
[This is a brew that takes into account bleed](https://homebrewery.naturalcrit.com/share/CyKa2EVxY-Om) and gives a visual indicator of it (which can be removed when sending to a printer).  It uses a root variable to set the bleed (in this case, 0.125in) and it adjusts the page size to suit.

It increases the size of the page in Homebrewery, and then also decreases the `.page` padding an equal amount, so that the layout doesn't shift.  It also requires a better footer graphic, since it needs to reach the edges of the wider page to account for the bleed.

When using this bit of CSS, a user will also need to increase the page size in the browser Print dialog to match.  Otherwise it'll just shrink the Homebrewery page down to fit inside a US Letter (or A4) page before creating the PDF.  

<details><summary>For convenience, here is the CSS</summary>

```css

:root {
  --bleed: .125in;
  --bleed-mark: lightblue; /* set to 'transparent' if no mark desired, such as before printing */
}

.page{
	width  : calc(215mm + var(--bleed) * 2);
	height : calc(279.4mm + var(--bleed) * 2);
  padding-top: calc(1.4cm + var(--bleed));
  padding-right: calc(1.9cm + var(--bleed));
  padding-bottom: calc(1.7cm + var(--bleed));
  padding-left: calc(1.9cm + var(--bleed));
  &:after {
    background-image: url(https://i.imgur.com/KS9eJQ2.png);
    height: calc(65px + var(--bleed));
    width: 110%;
    left: -5%;
    transform: scaleX(-1);
  }
  
  & .pageNumber {
    right: calc(2px + var(--bleed));
    bottom: calc(22px + var(--bleed));
  }
  &:before {
    content: '';
    position: absolute;
    outline: 1px solid var(--bleed-mark);
    width: calc(100% - var(--bleed) * 2);
    height: calc(100% - var(--bleed) * 2);
    top: var(--bleed);
    left: var(--bleed);
    
  }
}
```
</details>
