### ISSUE TITLE
wide toc in v3 isn't wide

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1595]
The wide table of contents has css which forces it into two columns (i.e. not wide)

![image](https://user-images.githubusercontent.com/2605467/130308302-e8aeb9c8-a37e-4a9d-b7d9-29d1677ec949.png)

````css
.page .toc.wide {
  column-count: 2;
  column-fill: auto;
  column-gap: .9cm;
  column-width: 7.68cm;
  -webkit-column-count: 2;
  -moz-column-count: 2;
  -webkit-column-width: 7.68cm;
  -moz-column-width: 7.68cm;
  -webkit-column-gap: .9cm;
  -moz-column-gap: .9cm;
}
````

(The H1 above the toc has it's own rule that busts out of those two columns)

In the legacy render, the toc outline is set to span the full page width.

![image](https://user-images.githubusercontent.com/2605467/130308338-1be09304-da77-462b-bc2b-e12691613f7f.png)
