### ISSUE TITLE
[v3] ToC `UL` element is uneven across columns

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1671]
These parts should be removed in v3 .less file.

```css
.page .toc > ul {          /* probably replace with .page .toc h1 { margin-bottom: .52cm; } */
	margin-top: .52cm;
}

/* and possibly this */

.page .toc ul li + li h3 {
	line-height: 1em;
}
```
<img width="756" alt="image" src="https://user-images.githubusercontent.com/58999374/132958445-b6435f8a-1f57-4be3-97c8-881aeef70eb4.png">
