### ISSUE TITLE
Awkward flow in navbar when brew title is long

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#2071]
This is a minor thing that's bothered me for awhile, sorry to open an issue on it:   When a brew title is long, and goes to two lines, the navbar height increases but the nav items come out looking odd.  

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/58999374/158091661-672c359f-c045-4dbb-865c-53fb96ec61c1.png">

A simple solution is to make the nav items flexboxes, and vertically center the fontawesome icons.  It looks like this:

<img width="1252" alt="two line title" title="two line title" src="https://user-images.githubusercontent.com/58999374/158091494-ccea6aec-ef7d-4c1d-8886-89c82a8ab871.png">

And with single line title:
<img width="1252" alt="single line title" title="single line title" src="https://user-images.githubusercontent.com/58999374/158091592-06455408-85bb-415a-abb9-f0ada35d0ec9.png">

The CSS changed is this:
```css
nav .navItem {
	-webkit-transition: background-color .25s ease;
	-moz-transition: background-color .25s ease;
	-o-transition: background-color .25s ease;
	transition: background-color .25s ease;
	padding: 8px 12px;
	cursor: pointer;
	background-color: #333;
	font-size: 10px;
	font-weight: 800;
	color: white;
	text-decoration: none;
	text-transform: uppercase;
	line-height: 13px;
	display: flex;  /* added these three items */
	align-items: center;
	justify-content: center;
}
```

I can create a PR quickly if interested.  I looked at it in both Chrome and FF.
