### ISSUE TITLE
Unwanted Code Blocks Appearing

### ISSUE THREAD

**Issue by RayOconnor** [naturalcrit/homebrewery#2738]
### Renderer

v3

### Browser

Chrome

### Operating System

MacOS

### Reproduce Code Block Bug

Code blocks will spontaneously appear if there is ever an HTML block with specific formatting...

```html
<div>
	This code is just wrapped in a div, but gets converted into a code block.
</div>
```

```html
<div>
	This code is wrapped in a div, but has a new line in between the content and the closing div tag. This prevents it from being turned into a code block.
	
</div>
```

#### More Context

If an author is using *just* default homebrewery, this problem can be mostly avoided. However, I have very custom styles and use HTML tags liberally. As a result I keep having random code blocks showing up in my V3 docs that do not exist using Legacy formatting.

### Reproduction
[This brew reproduces the behavior live](https://homebrewery.naturalcrit.com/share/9r6oMwFbUofi)

### Code

```gfm
This live brew example: https://homebrewery.naturalcrit.com/share/9r6oMwFbUofi

Uses the following markdown:
--------------------------------------------------
### Reproduce Code Block Bug

#### Expected...

Code blocks can be used in V3 by using .

```
This is an example of a proper code block
```
:::

#### Buggy Behavior

However, code blocks will spontaneously appear if there is ever an HTML block with specific formatting...

<div>
	This code is just wrapped in a div
</div>
:
<div>
	This code is wrapped in a div, but has a new line inbetween the content and the closing div tag.
	
</div>

:::
#### More Context

If an author is using *just* default homebrewery, this problem can be mostly avoided. However, I have very custom styles and use HTML tags liberally. As a result I keep having random code blocks showing up in my V3 docs that do not exist using Legacy formatting.
```

**Comment by ericscheid** [comment]
A line or paragraph that is indented with a tab or 4 spaces will get rendered as a code block.

This is standard Markdown behaviour. You can see it in action here on github, and also on reddit (for example).

Wrapping things in `<div>` elements can be a confounding situation, in that for some cases the text within a div doesn't get treated as a paragraph or line and passed through the Markdown renderer, but is instead simply rendered as text.

**Comment by ericscheid** [comment]
See also https://github.com/naturalcrit/homebrewery/issues/2092

**Comment by Gazook89** [comment]
Actually, HB is designed specifically to avoid writing HTML, but retains it as an option.

**Comment by 5e-Cleric** [comment]
> However, I have very custom styles and use HTML tags liberally.

mind if i ask what styles requires the use of other elements? are you using buttons or forms? inputs? lots of custom attributes?

**Comment by RayOconnor** [comment]
Surely,

Here are some of the custom classes I have that require me to use HTML tags here and there:

### Runts
This lets me force some words to a new line to correct "runts" or single-word lines at the ends of paragraphs.

```css
p.runt {
	/* Use to move text down from the text above it. */
	margin-top:0px !important;
}
```

```HTML
When a single word would spill onto the next line. like <p class="runt">right here.</p>
```

### Epistemology
When I want to include a piece of writing, I'll wrap a big block of content in a writing div that allows me to override numerous styles

```html
<h3>Epistomology</h3>

<div class="writing"> 
 
<h5>Title Here</h5>
	
Some handwritten blurbs can help to drop lore without being too intrusive.
	
It can be broken up into paragraphs like this. Take care to make this text very readable.
 
<span class="signature">- Author Signature</span>
</div>

<img class="writing-parchment right" style='top:444px; height:258px;'/>
```

<img width="327" alt="image" src="https://user-images.githubusercontent.com/6678233/225727181-b8527b6b-cbdb-4cd5-820e-8d724de9d186.png">

@Gazook89 That is useful to know. I am perhaps a fringe user that needs to create brews that do not look like Wizard's products such that I can sell them on Kickstarter.

I liberally change most of the default styles that ship with Homebrewery, though to your point, this does not require HTML, just CSS.

```css
/* Disable big first letter and first line override fonts. */
.pages h1+p:first-letter {
	all:unset;
}

.page h1+p:first-line {
	all:unset;
}

b {
	/* Bold fonts */
	font-family: 'Lora', serif;
	color: #245f8c;
}

strong {
	/* Bold fonts */
	font-family: 'Lora', serif;
	color: #245f8c;
}

b {
	/* Bold fonts */
	font-family: 'Lora', serif;
	color: #245f8c;
}

.pages p {
	font-family: 'EB Garamond', serif;
	font-size: 14px
}

.pages p+p {
	/* Rather than tabs to start paragraphs, leave a slight above space.*/
	text-indent:0;
	padding-top: 8px;
}

.pages ul+p {
	/* List styles */
	text-indent:0;
}
```

**Comment by Gazook89** [comment]
So all of those things can be done without using any HTML, but with using the custom markdown extensions built into the Homebrewery.  If you are using the v3 renderer (which you noted you are), you don't need to use HTML for any spans or divs. 

An html `<span>` is accomplished like this:
```html
Here is my text and {{color:red I want this part red}}

// Here is my text and <span style='color:red;'>I want this part red</span>
```

And a div is done like this:
```html
{{border:"1px solid red",red
Here is my div
}}

// <div class='red' style='border:1px solid red;'><p>Here is my div</p></div>
```

To your second example, it could be rewritten like this:
```
### Epistemology

{{writing
##### Title Here
Some handwritten blurbs can help to drop lore without being too intrusive.
	
It can be broken up into paragraphs like this. Take care to make this text very readable.
 
{{signature - Author Signature}}
}}

![alt text](https://image.url){writing-parchment,right,top:444px,height:258px}
```

You should try taking a look at the pre-made snippets in the editor menus-- they will demonstrate many of these concepts.  And take a look at this v3 reference guide I made a long time ago:  https://homebrewery.naturalcrit.com/share/14veTBQnfu3y-UXC6k9Fy1UlNLQyKpKpVv7J4ZI9zA4Wi

I think you will find that in 99% of cases you do not HTML.  Many many users do customization of their brews, only using CSS and the available markdown in HB.

**Comment by calculuschild** [comment]
> For the sake of discussion, it does seem a bit strange to adopt this particular convention of markdown.

We use all of the commonmark Markdown spec from a third-party package, so I wouldn't say we "adopted" it, because it's not like we are cherry-picking certain features and leaving others behind.

However it is a known issue that Markdown and HTML do not natively mix well. This is one of the primary reasons we designed  V3. It uses an expanded Markdown syntax specially made to bridge that gap so you can make Divs and Spans in a Markdown-like syntax without having to worry about these weird interactions you have run into (it's also much more legible for non-coders). As everyone else here has mentioned, all of the customization you have indicated can be done in the Homebrewery without the use of native HTML by taking advantage of V3's curly bracket `{{ }}` syntax.

**Comment by RayOconnor** [comment]
Interesting...

This is definitely a useful feature. It does require more specific use of css, but css only needs to be written once so that's not a disaster.

For example, to achieve the same styles
```CSS
div.writing span.signature {
	/* Create a signature for excerpts. */
	font-family: 'Nanum Brush Script', cursive;
	font-size: 24px;
}
```

Needs to become...

```CSS
div.writing div.signature p {
	/* Create a signature for excerpts. */
	font-family: 'Nanum Brush Script', cursive;
	font-size: 24px;
}
```

To affect the `<div class="block writing"><div class="signature"><p></p></div></div>` shape that is automatically rendered via the use of `{{` syntax instead.

A nagging part of me is concerned that my styles will break if `{{` starts to render as slightly different html, but as long future iterations maintain the functionality that is currently produced in V3, that is probably an unfounded concern.
