### ISSUE TITLE
Show tooltip of #id for headings

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#3313]
### Your idea:

To make it easier to author links to headings using the (auto-generated) `#id` attributes .. show that `id` in a tool tip.

This only needs a CSS tweak .. (the below needs to converted to less format though)

````css
.page h1,
.page h2,
.page h3,
.page h4,
.page h5 {
  cursor: alias;
}

.page h1:after,
.page h2:after,
.page h3:after,
.page h4:after,
.page h5:after {
  content: '#'attr(id);
  visibility: hidden;
  padding: 3px 5px 5px;
  background: #383838;
  font-size: 9px;
  font-family: courier;
  color: white;
  line-height: 12px;
  white-space: nowrap
  }

.page h1:hover:after,
.page h2:hover:after,
.page h3:hover:after,
.page h4:hover:after,
.page h5:hover:after {
  visibility: visible;
  opacity: 1
  }
````

**Comment by 5e-Cleric** [comment]
well, 

```
.page :is(h1, h2, h3, h4, h5 {
    cursor: alias;

    &::after {
        content: '#'attr(id);
        visibility: hidden;
        padding: 3px 5px 5px;
        background: #383838;
        font-size: 9px;
        font-family: courier;
        color: white;
        line-height: 12px;
        white-space: nowrap;
    }

    &:hover::after {
        visibility: visible;
        opacity: 1
    }
}
```

Or programatically add a title attribute with the same contents as the Id

**Comment by ericscheid** [comment]
> Or programatically add a title attribute with the same contents as the Id

Nah .. you'd need to find the right place to put that (in the header id generation code?) .. and doesn't lend itself to easy applying to any element with an `id` (but exclude the `<div class="page" id="p123">`.

**Comment by ericscheid** [comment]
A small addition to the above css to prevent it breaking Table of Contents layout..

```
.toc h2:after,
.toc h3:after,
.toc h4:after,
.toc h5:after {
  position: absolute;
  margin-left: 50px;
}
```

**Comment by 5e-Cleric** [comment]
This should only be added to the edit page, NOT the share page. I guess we could load it in template.js depending on the route...

https://developer.mozilla.org/en-US/docs/Web/CSS/@document would be of use if it wasn't deprecated.

**Comment by ericscheid** [comment]
Revised css to make tooltips an overlay hover, not inflow blocks

```css
.page h1,
.page h2,
.page h3,
.page h4,
.page h5 {
  cursor: alias;
  }

.page h1:after,
.page h2:after,
.page h3:after,
.page h4:after,
.page h5:after {
  position: absolute;
  margin-left: 5px;
  margin-top: 5px;
  content: '#'attr(id);
  x-visibility: hidden;
  padding: 3px 5px 5px;
  background: #383838;
  font-size: 9px;
  font-family: courier;
  color: white;
  line-height: 12px;
  white-space: nowrap
  }

.page h1:hover:after,
.page h2:hover:after,
.page h3:hover:after,
.page h4:hover:after,
.page h5:hover:after {
  visibility: visible;
  opacity: 1
  }

.toc h2:after, 
.toc h3:after, 
.toc h4:after, 
.toc h5:after {
  margin-left: 50px;
  margin-top: -10px;
}
```
