### ISSUE TITLE
Add US Letter Page Size snippet

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#3893]
### Your idea:

The default page size is US Letter, but the average new user shouldn't be expected to know that.

```css
/* US Letter Page Size */
.page {
	width  : 215.9mm; /* 8.5in */
	height : 279.4mm; /* 11in */
}
```

This is a low priority issue, perfect for a new contributor or anyone during Hacktober. 
Solution found = duplicate the existing A4 snippet code and substitute in the css above.
