### ISSUE TITLE
Add comment management

### ISSUE THREAD

**Issue by DarkMatter26** [naturalcrit/homebrewery#4133]
### Your idea:

Would it be possible to add a function to comment on the document?
To be activated according to who you want to give the possibility to Reader/Verifier/Author.

Either from the final rendering of the doc for a reader, or on the code for a verifier (read-only author, I don't know if this exists). 
Select a zone, add a remark/comment, fill in and validate.

Authors/readers/verifiers then have their comments displayed in another column or other, which they can comment on, close or accept.

The same principle as in Google Doc or Word, but simpler.

**Comment by G-Ambatte** [comment]
This is complicated, both for historic and functional reasons. Creating the new functionality would take time and testing; although the author invitation system works now. Admittedly, this may give a reviewer more access than is strictly necessary or desired.

---

1. I would envisage an `invitedReviewers` array, similar to the existing `invitedAuthors` array. When opening the Share page of a brew, if the logged in username matches an entry in `invitedReviewers`, then the commenting system will become available.
So the author MUST invite the reviewer, to prevent messaging from unknown parties.

2. The back end of the review system would be an array of objects that have a rough structure of:
```
{
  text: 'This is my review comment',
  author: username,
  createdAt: new Date,
  attachedTo: elementId,
  addressed: false,
  responseText: 'This is the author's response'
}
```
My thinking being that by attaching the review text to a specific element, it would not matter if later edits to the document moved that element to another page, as long as the element's ID remains consistent. As such, this would mean that only elements with IDs are valid targets for review comments - in practice, this would mean that the reviewer's notes for a paragraph of text might need to be attached to that paragraph's header.  
It's also worth noting that the pages ALSO have their own IDs, so review comments under this system _could_ be left on the page, although this eliminates the main benefit of attaching to an ID rather than a page.

3. I imagine the base system functionality would need to provide a new interface on the Share Page for reviewers to:
- create a review comment
- see their review comments 
- edit their review comments
- delete their review comments
- remove themselves as a reviewer

and a new interface on the Edit Page for authors to:
- invite a reviewer
- remove a reviewer's invite
- see ALL review comments, or filter by unaddressed or a particular reviewer
- mark a review as addressed
- add a response to the review
- delete a review completely

In summary, it's not impossible to do, but it is quite a lot of work.

**Comment by 5e-Cleric** [comment]
I'd wager we can leverage html and css comments to act as those objects, instead of creating a new object just for this... and am generally against communication between users inside the tool. Not feeling too strong for it or against it though.

**Comment by DarkMatter26** [comment]
It would be nice to have another "Comment Editor icon/tab", like the style editor which groups all the comments together
 so as not to distort the work area (I don't know if this is possible)

And, for the author, a "Comment Next button" to scroll through the comments, which displays the comment and displays the area concerned. in the worst case, then you go back to Brew editor to make the change.

**Comment by 5e-Cleric** [comment]
If so we'd stroll into 4 editors, a bit too much if you ask me.

**Comment by DarkMatter26** [comment]
That's about the only way I can think of that's currently used in HB to avoid mixing everything up (even though it's all in the same file).
The best thing would be to have a third area dedicated to comments open up when you click on this icon.
For example, to the right (or other, center, left) of the final document view,
This would allow you to scroll through the comments and process them as you go along, validating, rejecting, replying etc...

**Comment by ericscheid** [comment]
> as long as the element's ID remains consistent

this is not guaranteed, as ids for headings are auto-generated and are also sensitive to being moved around. That is, if the text of a header is edited, the id would change; and if a header that has the same text as another header is moved to a new ordinal in the sequence of duplicate headings then the id would also change. In the latter case, actually, the old id would still be valid, but would now be pointing at the wrong element (e.g. the "Actions" heading of monster block # 2).

> and am generally against communication between users inside the tool

Is there some assumption of commenting possibly occurring concurrently with either edits by an editor, or even comments from another commenter? Because handling edit-conflicts makes this tricky. Unless we store the comments seperately from the brew document to avoid edit clashes.

**Comment by 5e-Cleric** [comment]
> Is there some assumption of commenting possibly occurring concurrently with either edits by an editor, or even comments from another commenter? Because handling edit-conflicts makes this tricky. Unless we store the comments seperately from the brew document to avoid edit clashes.

I do not know, but if clashes were a thing, we can figure them out, differential synchronization is one of my favourite development subjects and i'd like to build a system like that at some point, but maybe not for comments...

**Comment by DarkMatter26** [comment]
> I do not know, but if clashes were a thing, we can figure them out, differential synchronization is one of my favourite development subjects and i'd like to build a system like that at some point, but maybe not for comments...

Simultaneous editing, whether for the main document via several authors or for adding, deleting or revising comments, is all the same, isn't it? :)

**Comment by 5e-Cleric** [comment]
if we ever implemented this, we might want different methods to handle the two, so not necessarily. If the subject sounds interesting to you, you might be interested in https://research.google.com/pubs/archive/35605.pdf this paper about it. It is very well written as papers go, and relatively short.

**Comment by JohneWilians** [comment]
Digital platform updates require structured oversight. A [Project Management Seminar and Master Class](https://www.iim.education/executive-seminars/project-management-seminar/) supports developers and team leads in managing change requests, setting priorities, and coordinating communication—ensuring successful implementation of new tools like the proposed comment management feature for naturalcrit/homebrewery.

**Comment by 5e-Cleric** [comment]
> Digital platform updates require structured oversight. A [Project Management Seminar and Master Class](https://www.iim.education/executive-seminars/project-management-seminar/) supports developers and team leads in managing change requests, setting priorities, and coordinating communication—ensuring successful implementation of new tools like the proposed comment management feature for naturalcrit/homebrewery.

Thank you for the suggestion. However, we’re already comfortable managing change requests, priorities, and internal communication. There are specific reasons why this feature hasn’t been implemented or prioritized, and we’re aware of the trade-offs involved.

**Comment by 5e-Cleric** [comment]
Definitely not the same, but in the meantime:

## Markdown
```md
{{comment,top:1in,left:4in
{{content
Lorem ipsum dolor sit amet

}}
}}
```

## CSS

```css

.page .comment {
  --bg:#eeb;
  background:var(--bg);
  height:25px;
  width:25px;
  border-radius:5px;
  position:absolute;
  box-shadow: 0 0 5px;
  
  &:after {
    position:Absolute;
    top:50%;
    left:50%;
    translate:-50% -50%;
    content: "\f4ad";
    font-size:15px;
    font-family: "Font Awesome 6 Free";
    font-weight: 400;
  }
  
  .content {
    position:absolute;
    right:-25px;
    top:50%;
    translate:100% -50%;
    width:fit-content;
    min-width:30ch;
    height:fit-content;
    min-height:3em;
    background:var(--bg);
    filter:drop-shadow(0 0 5px black);
    border-radius:inherit;
    padding:5px 10px;
    visibility:hidden;
    
    &:after {
      position:absolute;
      top:50%;
      left:-19px;
      translate:0 -50%;
      content:'';
      display:block;
      width: 0; 
      height: 0; 
      border-top: 10px solid transparent;
      border-bottom: 10px solid transparent; 
      border-right:20px solid var(--bg); 
    }
  }
  
  &:hover .content {
    visibility:visible;
  }
}
```


## Result when hovering over the comment element

![Image](https://github.com/user-attachments/assets/87088d86-8570-42b1-b5d4-bf981f68062c)
