### ISSUE TITLE
Horizontal line at bottom of page is too far forward

### ISSUE THREAD

**Issue by jimcullenaus** [naturalcrit/homebrewery#491]
Problem: The horizontal line at the bottom of each page has a z value of 100. This means that if you want an image to appear *above* it, that image needs a z-value of 101. Unfortunately, *this* in turn means it appears above text, sidebars (blockquotes in the MD), etc.

Required workaround currently: manually set `.phb::after{ z-index: -2;}`

Suggested solution: set `.phb::after{ z-index: -2;}` homebrewery-wide

Compare [this homebrew](http://homebrewery.naturalcrit.com/share/r10Ds9P9Z) as it is currently, with the same thing, but with lines 6–8 removed.

**Comment by Gazook89** [comment]
So this is one way:

```css
.page img {
	z-index:-2;	/* default to -2. but users can change to -1 to bring above footer, but below text */
}

.phb:after, .phb .pageNumber, .phb .footnote {
	z-index: -2;	
}
```

[example](https://homebrewery.naturalcrit.com/share/15BkVmG7YZyWElmHVmlBXc6wx51_6B5XdS5HpuYEra-in)

-----

At the same time, maybe it's worth revisiting .phb:after again and making it an explicit page element rather than pseudo-element.  As a single element it can bundle `.pageNumber` and `.footnote`.

```
{{footer
{{pageNumber 1}}
{{footnote PART 1 | SECTION NAME}}
}}
```
v3 syntax

```css
.page .footer {
	position:absolute;
	bottom:0;
	left:0;
	width:100%;
	height:50px;
	z-index:-2;
	padding:24px 100px 5px 100px;
	font-size:.8em;
	text-align:center;
	color:#c9ad6a;
	background-size:cover;
	background-image: url("data:image/png;base64.....
}
```

This would make it easier to forego the footer on individual pages rather than having to target specific pages (which may change) with `.phb:nth-of-type(20):after { display:none;}`.  The .footer div could also define the font family, color, size so those properties could all be changed together rather than for each constituent piece.  But still retain the ability to change each piece if wanted.   And, if there was a text node inside `{{footer  }}` it could be positioned to fit under the bar graphic.....this would be a clear way of allowing users to add a fan content policy or whatever else.

[Here is another example brew (same content, different example).](https://homebrewery-stage.herokuapp.com/share/j2rQYkr7GBRR)

<img width="863" alt="image" src="https://user-images.githubusercontent.com/58999374/132919748-9ac9205f-6e5a-4df5-8142-0832ec415ca1.png">
